# Site settings
title: Juruseni - Online Marketplace
description: Marketplace untuk seniman
url: http://juruseni.github.io
baseurl: ''

gems: ['jekyll-redirect-from']
exclude: ['README.md', 'Gemfile']
